/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ccipTransferorSol from "./CCIPTransferor.sol";
export * as sameChainPaymentSol from "./SameChainPayment.sol";
