/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ccipTransferorSol from "./CCIPTransferor.sol";
export type { ccipTransferorSol };
import type * as sameChainPaymentSol from "./SameChainPayment.sol";
export type { sameChainPaymentSol };
