/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AttestTest__factory } from "./AttestTest__factory";
export { Attester__factory } from "./Attester__factory";
